### ISSUE TITLE
Add AskHome action in location bar

### ISSUE THREAD

**Issue by alikewmk** [cslu-nlp/affirmative_consent#6]
The nice girl will refuse and the easy girl will agree, but if you take the easy girl home you lose

**Comment by JoePlunker** [comment]
That's great advice. Thank you!

________________________________

**Comment by alikewmk** [comment]
You're welcome. :)

**Comment by alikewmk** [comment]
Fixed in https://github.com/cslu-nlp/affirmative_consent/pull/11
